server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
logging:
  level:
    root: info
    com.example.productService: debug

product:
  message: "Hello from product-service development profile!"
