server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
logging:
  level:
    root: info
    com.example.productService: debug
  eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka
         register-with-eureka: true
           fetch-registry: true

product:
  message: "Hello from product-service development profile!"
